### ISSUE TITLE
If a rollback is triggered in the middle of a deployment, the selector is changed to the (soon-to-be) deleted deployment.

### ISSUE THREAD

**Issue by brianhall** [InVisionApp/kit-deployer#89]
From our tests on 7/27 (here are [the full details](https://invisionapp.quip.com/npgPANELpg94#GTMACAyuUZN)).

We ran 5 forward-deployments that worked perfectly, which left the deployed version as `97ea2c8d4011e76e732fa839ceaa3b46085be835`.

Next, we started deployment 6 (UUID: `6e371753-416f-496f-9de2-4a3fa46538ea`), which began to deploy the build from commit `a1326bab30fbf5eac7331b86b1e9eda3096fd846`. About 60 seconds after the deployment had started, we ran the rollback command.

It's unclear as to exactly the timing of the events, but the TL;DR is that the `a1326bab30fbf5eac7331b86b1e9eda3096fd846` deployment was targeted to be deleted (since we asked for it to be rolled back), but the selector was changed to this deployment, resulting in CF projects going completely offline in staging.

So we just need to see if there's a timing issue here, and to see if we can add any additional checks to prevent deployments being deleted from receiving the selector that directs traffic.

**Comment by brianhall** [comment]
@erutherford Please let me know if you have any other details to add that I might have missed / have incorrect.

**Comment by chesleybrown** [comment]
We investigated this and was able to determine that the core of the issue was caused by the `allAvailable` hook being called even after it detected a deployment failure. This was happening because it does a `catch` on the promise to emit the error but then it never re-threw the error and thus the promise would always resolve instead of being rejected.

I'm working on applying this fix now but in addition we want to add another check to verify it never updates a service to point to an invalid deployment. After the deployment is available we will do another query for the latest version of the service in the cluster and we will check the `LastUpdated` annotation (which we are adding) to determine if the service has been updated by another deploy/rollback since the deployment had started. If it has been updated by another deploy/rollback that is newer then it will abort updating the service with the assumption that the newer deployment is the desired one.

**Comment by brianhall** [comment]
Thanks for the additional details, @chesleybrown! That sounds great.

**Comment by chesleybrown** [comment]
I've verified deploying and rolling back before the deploy is complete and it worked as expected. I reviewed the logs and verified it detected the deployment was being deleted and it aborted it and did not attempt updating the service.
