### ISSUE TITLE
Ability to freely switch between deployment strategies

### ISSUE THREAD

**Issue by chesleybrown** [InVisionApp/kit-deployer#96]
We currently support two deployment strategies: `fast-rollback` and `rolling-update`

However once you deploy using one strategy you cannot easily switch to using the other strategy. Instead if you try deploying using a different strategy than you previously used for that service things will break in strange ways (leftover deployments or pointing traffic to a deployment that isn't available yet, etc).

We should build into the two supported strategies such that you can easily switch between them without concern.

# Solution

- [x] `kit-deployer` will dynamically add the labels we need for the deployment strategy (currently we depend on them being manually configured correctly via deploymentizer templating). These labels will be `id`, `service` and `strategy`. These labels will always be set regardless of strategy used.
- [x] Document `id`, `service` and `strategy` as reserved labels for kit
- [x] Throw error if any reserved labels have been manually set
- [x] Update `rolling-update` strategy to only deploy `service` manifests _after_ all deployments are available (just like `fast-rollbacks` currently does)
- [x] After a deploy is available the strategy should delete all deployments pertaining to other strategies for this service (example: delete where `strategy!=fast-rollback` or `strategy!=rolling-update`)
- [x] After a deploy is available the strategy should delete all ReplicaSets pertaining to other strategies for this service (example: delete where `strategy!=fast-rollback` or `strategy!=rolling-update`)

**Comment by chesleybrown** [comment]
# Solution

If the following changes are made we will be able to freely alternate between strategies without any downtime or manual cleanup intervention.

1. `kit-deployer` will dynamically add the labels we need for the deployment strategy (currently we depend on them being manually configured correctly via deploymentizer templating). These labels will be `id`, `service` and `strategy`. These labels will always be set regardless of strategy used.
1. Document `id`, `service` and `strategy` as reserved labels for kit
1. Throw error if any reserved labels have been manually set
1. After a deploy is available the strategy should delete all deployments pertaining to other strategies for this service (example: delete where `strategy!=fast-rollback` or `strategy!=rolling-update`)
1. Update `rolling-update` strategy to only deploy `service` manifests _after_ all deployments are available (just like `fast-rollbacks` currently does)

# Notes

- We originally thought ReplicaSets would be orphaned when adding labels to deployment selectors but this thread says this is not the case: https://github.com/kubernetes/kubernetes/issues/14894#issuecomment-297118553 we may need to verify this?

**Comment by c1freitas** [comment]
1) If we are always setting these values, why not have them as part of the template? I prefer having them discoverable vs "magic" adding them at deployment time.

**Comment by chesleybrown** [comment]
Because they a core piece of the strategy logic. So a number of reasons why I strongly think it should be handled by kit:

1. Avoid human error from misconfiguration of the labels
1. If new labels are needed for more strategies we don't have to manually update templates for the strategy to work
1. Setting these labels manually requires deep knowledge of how kit strategies work. Sure today we understand why `id`, `service` and `strategy` are set on the template... but anyone else coming in wouldn't have any idea why they are set, which ones are required and what they can possibly change them to. Any misconfiguration of these labels can have disastrous effects.
1. Just less for us to manually manage in our templates. Less is more.
1. I think I could go on... but I feel these reasons are enough to justify it

**Comment by chesleybrown** [comment]
I had thought on that too, but because I'm going to verify they aren't manually set means we don't have to worry about accidentally overwriting the values and deploying it as it will catch it before it ever deploys it.

**Comment by c1freitas** [comment]
Will it throw an error if they are already set?

We will need to clean up the existing manifest with these values. I think it's just the test rosie resources...

**Comment by erutherford** [comment]
We've actually seen the replica sets get orphaned and it's in their [documentation](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#label-selector-updates) that it'll happen.  Basically, it only happens if you add or update a label in the selector.

At this point, only the test rosie services have the deployment-strategy labels and I don't think [Manuel's PR](https://github.com/InVisionApp/kubernetes-coreos/pull/1918) adding the initial fast-rollback labels was ever merged.

**Comment by chesleybrown** [comment]
I've updated the todo list to include a task to delete orphaned ReplicaSets as part of the cleanup process.

**Comment by c1freitas** [comment]
_scope creep_ 😆

**Comment by c1freitas** [comment]
I thought of a potential issue with this approach. Once this is implemented it will not allow SRE's to _manually_ deploy a manifest for an existing service, since any generated manifests will not have the correct selectors (for pods/svc) and would match both the existing deployment pods and the new one pushed out. They could still potentially do this by also updating the `svc` object, but the timing of that could be tricky.

I believe this will still work for initial provisioning, but once a service has been deployed via `kit` with these dynamic selectors, there is no going back to a manual `apply` command. 

This is something well will need to make the SRE's aware of. I am not sure how often they do these manual fixes, but after this implementation, it will have to stop.

**Comment by chesleybrown** [comment]
Very valid point. But they would have had to make manual changes to the deployment file before applying it with our current implementation of `fast-rollback` because we dynamically rename the deployment file as well as adding annotations such as `LastUpdated`, `UUID`, etc. So regardless of the changes proposed in this Issue, we _should not_ be doing anymore manual applies.
